#!/bin/bash

set -e

source "$(dirname "$0")/../utils/log.sh"
source "$(dirname "$0")/../utils/secrets.sh"

log_header "Installing and Configuring Nginx"

# Check if Nginx is already installed
NGINX_ALREADY_INSTALLED=false
if command -v nginx &> /dev/null; then
    NGINX_ALREADY_INSTALLED=true
    log_info "Nginx is already installed: $(nginx -v 2>&1)"
fi

# Get configuration mode
NGINX_MODE=$(get_secret "nginx.mode")
DOMAIN=$(get_secret "nginx.domain")

if [ "$NGINX_ALREADY_INSTALLED" = true ] && [ "$NGINX_MODE" = "add" ]; then
    log_info "Adding new app configurations to existing Nginx setup..."
elif [ "$NGINX_ALREADY_INSTALLED" = true ] && [ "$NGINX_MODE" = "reset" ]; then
    log_warn "Re-setting up Nginx (backing up existing configs)..."
    sudo mkdir -p /etc/nginx/sites-available.backup
    sudo cp -r /etc/nginx/sites-available/* /etc/nginx/sites-available.backup/ 2>/dev/null || true
    sudo rm -f /etc/nginx/sites-enabled/*
else
    # Fresh installation
    log_progress "Installing Nginx..."
    sudo apt-get update -qq
    sudo apt-get install -y nginx
    log_success "Nginx installed"
fi

# Disable default site if it exists
if [ -f "/etc/nginx/sites-enabled/default" ]; then
    log_progress "Disabling default Nginx site..."
    sudo rm -f /etc/nginx/sites-enabled/default
    log_success "Default site disabled"
fi

# Get app count
APP_COUNT=$(get_secret "nginx.app_count")

if [ -z "$APP_COUNT" ] || [ "$APP_COUNT" -eq 0 ]; then
    log_warn "No apps configured for Nginx"
else
    log_progress "Configuring $APP_COUNT app(s)..."
    
    # Get all app names from secrets
    APP_NAMES=$(jq -r '.nginx.apps | keys[]' "$SECRETS_FILE" 2>/dev/null || echo "")
    
    for APP_NAME in $APP_NAMES; do
        log_info "Configuring app: $APP_NAME"
        
        APP_PORT=$(get_secret "nginx.apps.$APP_NAME.port")
        ROUTING_TYPE=$(get_secret "nginx.apps.$APP_NAME.routing_type")
        ROUTING_VALUE=$(get_secret "nginx.apps.$APP_NAME.routing_value")
        
        # Sanitize app name for filename
        SAFE_APP_NAME=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
        
        CONF_FILE="/etc/nginx/sites-available/app-${SAFE_APP_NAME}.conf"
        
        if [ "$ROUTING_TYPE" = "subdomain" ]; then
            # Subdomain configuration
            FULL_DOMAIN="${ROUTING_VALUE}.${DOMAIN}"
            
            sudo tee "$CONF_FILE" > /dev/null << EOF
# Nginx configuration for $APP_NAME
# Generated by EC2 Bootstrap Setup

upstream ${SAFE_APP_NAME}_backend {
    server localhost:${APP_PORT};
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${FULL_DOMAIN};

    client_max_body_size 100M;

    location / {
        proxy_pass http://${SAFE_APP_NAME}_backend;
        proxy_http_version 1.1;
        
        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF
        else
            # Path-based configuration
            PATH_VALUE=$(echo "$ROUTING_VALUE" | sed 's/^\///')  # Remove leading slash
            
            sudo tee "$CONF_FILE" > /dev/null << EOF
# Nginx configuration for $APP_NAME
# Generated by EC2 Bootstrap Setup

upstream ${SAFE_APP_NAME}_backend {
    server localhost:${APP_PORT};
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    client_max_body_size 100M;

    location /${PATH_VALUE} {
        proxy_pass http://${SAFE_APP_NAME}_backend;
        proxy_http_version 1.1;
        
        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF
        fi
        
        # Enable the site
        sudo ln -sf "$CONF_FILE" "/etc/nginx/sites-enabled/app-${SAFE_APP_NAME}.conf"
        log_success "Configured $APP_NAME ($ROUTING_TYPE)"
    done
fi

# Configure MailHog if it's in the setup
if has_secret "mailhog.routing_type"; then
    log_progress "Configuring MailHog proxy..."
    
    MAILHOG_ROUTING_TYPE=$(get_secret "mailhog.routing_type")
    MAILHOG_ROUTING_VALUE=$(get_secret "mailhog.routing_value")
    MAILHOG_AUTH_ENABLED=$(get_secret "mailhog.auth_enabled")
    
    MAILHOG_CONF="/etc/nginx/sites-available/mailhog.conf"
    
    if [ "$MAILHOG_ROUTING_TYPE" = "subdomain" ]; then
        MAILHOG_DOMAIN="${MAILHOG_ROUTING_VALUE}.${DOMAIN}"
        
        sudo tee "$MAILHOG_CONF" > /dev/null << EOF
# Nginx configuration for MailHog
# Generated by EC2 Bootstrap Setup

server {
    listen 80;
    listen [::]:80;
    server_name ${MAILHOG_DOMAIN};

    location / {
EOF
        
        # Add basic auth if enabled
        if [ "$MAILHOG_AUTH_ENABLED" = "true" ]; then
            MAILHOG_USER=$(get_secret "mailhog.auth_user")
            MAILHOG_PASSWORD=$(get_secret "mailhog.auth_password")
            
            # Install apache2-utils for htpasswd
            if ! command -v htpasswd &> /dev/null; then
                sudo apt-get install -y apache2-utils
            fi
            
            # Create htpasswd file
            HTPASSWD_FILE="/etc/nginx/.htpasswd-mailhog"
            echo "$MAILHOG_PASSWORD" | sudo htpasswd -ci "$HTPASSWD_FILE" "$MAILHOG_USER"
            
            sudo tee -a "$MAILHOG_CONF" > /dev/null << EOF
        auth_basic "MailHog Admin Area";
        auth_basic_user_file /etc/nginx/.htpasswd-mailhog;
        
EOF
        fi
        
        sudo tee -a "$MAILHOG_CONF" > /dev/null << EOF
        proxy_pass http://localhost:8025;
        proxy_http_version 1.1;
        
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
    else
        # Path-based MailHog config
        PATH_VALUE=$(echo "$MAILHOG_ROUTING_VALUE" | sed 's/^\///')
        
        sudo tee "$MAILHOG_CONF" > /dev/null << EOF
# Nginx configuration for MailHog (path-based)
# Generated by EC2 Bootstrap Setup

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location /${PATH_VALUE} {
EOF
        
        if [ "$MAILHOG_AUTH_ENABLED" = "true" ]; then
            MAILHOG_USER=$(get_secret "mailhog.auth_user")
            MAILHOG_PASSWORD=$(get_secret "mailhog.auth_password")
            
            if ! command -v htpasswd &> /dev/null; then
                sudo apt-get install -y apache2-utils
            fi
            
            HTPASSWD_FILE="/etc/nginx/.htpasswd-mailhog"
            echo "$MAILHOG_PASSWORD" | sudo htpasswd -ci "$HTPASSWD_FILE" "$MAILHOG_USER"
            
            sudo tee -a "$MAILHOG_CONF" > /dev/null << EOF
        auth_basic "MailHog Admin Area";
        auth_basic_user_file /etc/nginx/.htpasswd-mailhog;
        
EOF
        fi
        
        sudo tee -a "$MAILHOG_CONF" > /dev/null << EOF
        proxy_pass http://localhost:8025;
        proxy_http_version 1.1;
        
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
    fi
    
    sudo ln -sf "$MAILHOG_CONF" "/etc/nginx/sites-enabled/mailhog.conf"
    log_success "MailHog proxy configured"
fi

# Test Nginx configuration
log_progress "Testing Nginx configuration..."
if sudo nginx -t 2>&1 | grep -q "successful"; then
    log_success "Nginx configuration is valid"
else
    log_error "Nginx configuration test failed"
    sudo nginx -t
    exit 1
fi

# Restart Nginx
log_progress "Restarting Nginx..."
sudo systemctl restart nginx
sudo systemctl enable nginx

if systemctl is-active --quiet nginx; then
    log_success "Nginx is running"
else
    log_error "Nginx failed to start"
    exit 1
fi

log_info "Nginx configurations created:"
ls -1 /etc/nginx/sites-enabled/ | while read conf; do
    echo "  - $conf"
done

log_success "Nginx installation and configuration complete"
